### ISSUE TITLE
Report queries

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/comp353#24]
- [x] Number of employees with Premium Employee plan with working hours less than
60 hrs/month. 

- [x] Number of Premium contracts delivered in more than 10 business days having
more than 35 employees with “Silver Employee Plan”. 

- [x] Make a report to compare the delivery schedule of "First deliverable" of all type
of contracts (Premium/Diamond etc.) in each month of year 2017.

**Comment by FrankSauve** [comment]
May need to include these ones too 
![image](https://user-images.githubusercontent.com/13418355/43978208-7a5c64ac-9cb4-11e8-9c75-a298dc837ca2.png)

**Comment by Lior-za** [comment]
Sarb has finished: 1, 4 & 5.

**Comment by Lior-za** [comment]
2 and 3 are done!
